SET SCHEMA PUBLIC;

CREATE TABLE ACCOUNT_HOLDER
(
    ID serial PRIMARY KEY,
    CPF  varchar NOT NULL UNIQUE,
    NAME  varchar NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE ACCOUNT
(
    ID serial PRIMARY KEY,
    ACCOUNT_HOLDER_ID  int NOT NULL,
    BALANCE  numeric(12,4) NOT NULL,
    BANK_BRANCH  varchar NOT NULL,
    ACTIVE  BOOLEAN NOT NULL,
    BLOCKED  BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NULL,
    FOREIGN KEY (ACCOUNT_HOLDER_ID) REFERENCES ACCOUNT_HOLDER (ID)
);

CREATE TABLE ACCOUNT_STATEMENT
(
    ID serial PRIMARY KEY,
    ACCOUNT_ID  int NOT NULL,
    AMOUNT  numeric(12,4) NOT NULL,
    OPERATION_TYPE  varchar NOT NULL,
    DESCRIPTION  varchar NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT type_check CHECK (OPERATION_TYPE IN ('CREDIT', 'DEBIT', 'CANCEL', 'REVERSAL')),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID)
);


